language: elixir
sudo: false
elixir:
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 19.3
  - 20.3
  - 21.0
matrix:
  exclude:
    - elixir: 1.8
      otp_release: 19.3
script:
  - "MIX_ENV=test mix do deps.get, compile"
notifications:
  recipients:
    - chris@chrishildebrand.net
